name: branche

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/doc/**'
      - '**/README.md'
      - '**/LICENSE'
      - '**/.typo-ci.yml'
jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
  
    - name: Restore nuget packages
      run: msbuild -t:restore
      working-directory: src
    
    - name: Build sources
      run: msbuild /p:Configuration=Release
      working-directory: src
    
    - name: VSTest
      run: vstest.console.exe **/bin/**/Dependencies.Viewer.UnitTests.dll /Platform:x64
      working-directory: src
  
    - uses: actions/upload-artifact@v2
      with:
        name: DependenciesViewer
        path: Build/Release/
